Content.Shared/Movement/Pulling/Systems/PullingSystem.cs, Content.Shared/_CorvaxGoob/Movement/Pulling/CanChokeGrabComponent.cs, Resources/Prototypes/Entities/Mobs/Player/humanoid.yml, Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/GameRules/roundstart.yml, Resources/Prototypes/Roles/Jobs/Civilian/chef.yml, Resources/Prototypes/Roles/Jobs/Security/warden.yml, Resources/Prototypes/_CorvaxGoob/Roles/Jobs/Security/wardenHelper.yml, Resources/Prototypes/_DV/CosmicCult/events.yml, Resources/Prototypes/_DV/CosmicCult/roundstart.yml, Resources/Prototypes/_Goobstation/GameRules/midround.yml, Resources/Prototypes/_Goobstation/GameRules/roundstart.yml, Resources/Prototypes/_Goobstation/Heretic/GameRules/roundstart.yml, Resources/Prototypes/_Goobstation/Wizard/gamerules_wizard.yml, Resources/Prototypes/_Goobstation/_Pirates/game_ticking.yml
=> Revert CanChokeGrab system

Content.Client/Robotics/UI/RoboticsConsoleBoundUserInterface.cs, Content.Client/Robotics/UI/RoboticsConsoleWindow.xaml, Content.Client/Robotics/UI/RoboticsConsoleWindow.xaml.cs, Content.Server/Robotics/Systems/RoboticsConsoleSystem.cs, Content.Server/Silicons/Borgs/BorgSystem.Transponder.cs, Content.Shared/Robotics/Components/RoboticsConsoleComponent.cs, Content.Shared/Robotics/RoboticsConsoleUi.cs, Resources/Locale/en-US/_corvaxgoob/research/components/robotics-console.ftl, Resources/Locale/en-US/_corvaxgoob/research/technologies.ftl, Resources/Locale/ru-RU/_corvaxgoob/research/components/robotics-console.ftl, Resources/Locale/ru-RU/_corvaxgoob/research/technologies.ftl, Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_CorvaxGoob/Recipes/Lathes/Packs/circuitboards.yml, Resources/Prototypes/_CorvaxGoob/Recipes/Lathes/circuit_boards.yml, Resources/Prototypes/_CorvaxGoob/Research/experimental.yml, Resources/Prototypes/_Goobstation/Research/experimental.yml
https://github.com/space-syndicate/space-station-14-next/pull/43
Обновил под текущую систему латов + добавил возможность крафтить плату оверлорда(проще говоря синтетики боги, люди ВЫ ВСЕ ГОВНО).
=> [NEXT PORT] Изменяемые законы боргов by FireNameFN

Resources/ConfigPresets/Corvax/common.toml
[sync #3155](https://github.com/space-syndicate/space-station-14/pull/3155)
Изменено время
- в лобби 6 > 4
- до рестарта 2 > 4
=> Change lobby & restart time

Resources/Maps/_CorvaxGoob/Stations/Chloris/Shuttles/corvax_nt-sec-overseer.yml, Resources/Prototypes/_CorvaxGoob/Maps/Pools/corvax.yml, Resources/Prototypes/_CorvaxGoob/Maps/Stations/corvax_chloris.yml
На Хлорис и Астру добавлено:
- Сило
- Научный ТехФаб
- Инженерный ТехФаб
- "Автолат" заменен на "ТехФаб снабжения"
- Стеклянный короб [Законодатель, Заполненный]
**Офицер Синего Щита**
- Шкаф офицера Синего Щита [МАППИТЬ ЭТО, Уникальный, Заполненный]
- Комод [Заполненный, Синий Щит]
**Представитель НТ**
- Шкаф Представителя Нанотрейзен [МАППИТЬ ЭТО, Уникальный, Заполненный]
- Папка Центком
- Кристалл суперматерии
- Эмиттеры
- Коллекторы радиации
- Датчик газовой трубы [Суперматерия,
Холодная]
- Датчик газовой трубы [Суперматерия,
Горячая]
- Сенсор воздуха
- Воздушная сигнализация
- Пассивная вентиляция
- Скрубберы
- Радиаторы
- Хранилище скафандра [HEV, Заполненный]
- Уборочная машина (спавнер)
- Ключи от уборочной машины
- Квадроцикл (спавнер)
- Ключи от квадроцикла
- Сегвей (спавнер)
- …
=> [Maps] Astra&Chloris update

Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml
=> Invert aghost speed

Resources/Prototypes/Entities/Mobs/Player/ShuttleRoles/settings.yml, Resources/Prototypes/_Goobstation/Entities/Mobs/Player/ShuttleRoles/settings.yml, Resources/Prototypes/_Goobstation/Entities/Mobs/Player/admeme.yml
Починил [это](https://discord.com/channels/919301044784226385/1404371165023309915) и [это](https://discord.com/channels/919301044784226385/1404706195306188830)
**Список изменений**
:cl:
- fix: Починены навыки у гостролей с шаттлов!
- fix: Починены навыки у ролей ЦК!
=> [FIX] Fix some skills for some roles

Content.Client/_CorvaxGoob/TTS/TTSSystem.Announcements.cs, Content.Client/_CorvaxGoob/TTS/TTSSystem.cs, Content.Server/Announcements/AnnounceCommand.cs, Content.Server/Communications/CommunicationsConsoleSystem.cs, Content.Server/_CorvaxGoob/TTS/TTSSystem.Announcements.cs, Content.Server/_CorvaxGoob/TTS/TTSSystem.cs, Resources/Prototypes/_CorvaxGoob/audio_presets.yml
Упростил озвучку ТТС объявлений. До этого жаловались, что она слишком долгая. Исправил проигрывание, теперь озвучка будет работать даже в лобби. Новая версия прикреплена в медиа
https://github.com/user-attachments/assets/dfad582f-ba0a-4a93-a6ef-ac3cb256d444
:cl: KillanGenifer
- tweak: Была упрощена длительность озвучки объявлений
=> TTS announcements tweak

Resources/Locale/ru-RU/_Goobstation/tiles/tiles.ftl, Resources/Locale/ru-RU/_Shitmed/tiles/tiles.ftl
Локализация абдуктор и бингл тайлов
=> [Locale] Tiles

Content.Server/Chemistry/EntitySystems/InjectorSystem.cs, Content.Server/Construction/ConstructionSystem.Initial.cs, Content.Server/Construction/ConstructionSystem.Interactions.cs, Content.Server/Construction/ConstructionSystem.cs, Content.Server/Implants/ImplanterSystem.cs, Content.Server/Kitchen/EntitySystems/KitchenSpikeSystem.cs, Content.Server/Kitchen/EntitySystems/SharpSystem.cs, Content.Server/Physics/Controllers/MoverController.cs, Content.Server/Weapons/Ranged/Systems/GunSystem.cs, Content.Server/_CorvaxGoob/Skills/SkillsSystem.cs, Content.Shared/_CorvaxGoob/CCCVars/CCCVars.cs, Content.Shared/_CorvaxGoob/Skills/SharedSkillsSystem.cs, Resources/ConfigPresets/Corvax/main.toml
Починен имплантер навыков. Навыки отключены на Мейне
Добавлен новый серверный CVar, отвечающий за навыки.
**Список изменений**
:cl: KillanGenifer
- tweak: Навыки отключены на Мейне
- fix: Исправлен имплантер с навыками
=> Skills tweak

Content.Client/_CorvaxGoob/TintedWindow/TintedWindowSystem.cs, Content.Shared/_CorvaxGoob/TintedWindow/TintedWindowComponent.cs, Resources/Locale/ru-RU/_corvaxgoob/entities/structures/windows/windows.ftl, Resources/Prototypes/_CorvaxGoob/Entities/Structures/Windows/tinted.yml
Перенесено из https://github.com/space-syndicate/space-station-14-next/pull/525
=> PR : Tinted window

Content.Server/Chemistry/EntitySystems/InjectorSystem.cs, Content.Server/Construction/ConstructionSystem.Initial.cs, Content.Server/Construction/ConstructionSystem.Interactions.cs, Content.Server/Implants/ImplanterSystem.cs, Content.Server/Kitchen/EntitySystems/KitchenSpikeSystem.cs, Content.Server/Kitchen/EntitySystems/SharpSystem.cs, Content.Server/Physics/Controllers/MoverController.cs, Content.Server/Weapons/Ranged/Systems/GunSystem.cs, Content.Server/_CorvaxGoob/Skills/SkillsSystem.cs, Content.Shared/_CorvaxGoob/Skills/SharedSkillsSystem.cs, Resources/Prototypes/_Shitmed/Actions/abductor.yml
Упростил проверку на навыки в случае отключения с помощью CVar'а, пофиксил взаимодействия с консолью абдукторов
=> Skills check optimization + temporary abductors fix

Resources/Locale/ru-RU/_corvaxgoob/ghost/roles/ghost-role-component.ftl
Вернул потерянную локаль гост роли и изменил описание, более явно указав на навыки и знания.
Обновление карты CorvaxGlacier:
- Служба безопасности накрыла тайник воришки офисных кресел, там было обнаружено целых 100 украденных офисных кресел! Все они были возвращены на свои места, правда злоумышленник успел скрутить колесики почти на всех...
- Добавлена панель управления турелями у ИИ.
- Автолат в общей комнате с инструментами заменен на сервисный техфаб.
- Из СБ хранилища в перме было вынесено все летальное оружие.
- Атмосфера пермы теперь не зависит от атмосферы на улице.
=> [Maps] CorvaxGlacier office chair and locale fix

Resources/ConfigPresets/Corvax/mrp.toml
ya eblan
Терминал теперь спавнится
=> Terminal path fix

Resources/Prototypes/_CorvaxGoob/Entities/Mobs/NPCs/human.yml
Обновление карты CorvaxGlacier:
- Исправлены навигационные маяки, теперь на картах вновь должны быть виден их текст.
- Исправлен шлюз священника.
- Скамейки в зонах отдыха атмосов заменены на диваны.
- Автоматы с едой заменены на хайпоп версию, халява закончилась.
- В снабжении добавлен ПочтаШкаф.
- В допросную добавлено зеркало Гезелла. (Пока что включина миграция, но как поправят, будет нормально).
- У контрабандистов теперь случайная внешность и TTS для более разнообразного отыгрыша.
Контрабандисты:
=> [Maps] CorvaxGlacier fixes and small update

Resources/Locale/ru-RU/_corvaxgoob/recipes/tags.ftl, Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/_CorvaxGoob/Recipes/Crafting/improvised.yml, Resources/Prototypes/_CorvaxGoob/Recipes/Crafting/improvised/makeshift_laser.yml
https://github.com/space-syndicate/space-station-14-next/pull/524
=> [PORT] crafting WeaponMakeshiftLaser

Resources/Prototypes/Entities/Objects/Weapons/Melee/baseball_bat.yml
Изменил размер бейсбольной биты для того чтобы она лезла в микроволновку.
Бита используется для рецепта хоум ран бургера поэтому должна лезть в микроволновку.
Изменил значение Large на Normal.
=> baseball bit size fix

Content.Server/_CorvaxGoob/Jobs/MrpJobSystem.cs, Content.Server/_CorvaxGoob/Jobs/StationJobsSystem.Mrp.cs, Content.Shared/_CorvaxGoob/CCCVars/CCCVars.cs, Content.Shared/_CorvaxGoob/Jobs/MrpJobSystem.cs, Content.Shared/_CorvaxGoob/Roles/JobPrototype.Mrp.cs, Resources/ConfigPresets/Corvax/main.toml
Cvar позволяющий отключать мрп должности для лрп серверов или лрп должности для мрп серверов.
Этот pr добавляет cvar jobs.mrp_enabled и систему с прототипом. 
При выключеном cvar все должности с признаком mrp: true будут отключены, а с false работать
При включеном cvar все должности с признаком mrp: true будут работать, а с false отключены.
**Список изменений**
:cl:Krosus
- add: Cvar для отключения должностей.
=> CvarMrpJob

Content.Goobstation.Common/CCVar/CCVars.Goob.cs
Параметр "Отображать подробное описание при осмотре" отключён по умолчанию. 
Потому.
Отсутствуют.
**Список изменений**
:cl:
- add: Параметр "Отображать подробное описание при осмотре" отключён по умолчанию.
=> EchoPointing option

Content.Goobstation.Server/Ghostbar/GhostBarSystem.cs, Content.Server/Objectives/Systems/PickObjectiveTargetSystem.cs, Content.Server/_CorvaxGoob/Objectives/Components/AntagObjectiveImmunityComponent.cs
Посетители ghostbar более не могут быть целями антагонистов.
Потому что.
Добавлен компонент-пустышка `AntagObjectiveImmunityComponent`, добавлена проверка на этот компонент при выборе цели в `PickObjectiveTargetSystem.cs`.
Не требуется
Отсутствуют.
:cl:
- fix: Посетители GhostBar теперь не могут быть целью антагонистов!
=> Antag objective immunity

.github/workflows/publish.yml
=> trying fix publish

Resources/Locale/ru-RU/corvax/speech/speech-chatsan.ftl, Resources/Prototypes/Accents/word_replacements.yml
=> [Locale] Chatsan R&D
